# zsh shpec build draft
language: zsh
env:
  - SHELL=zsh
install:
  # install antigen
  - curl -L git.io/antigen > ~/antigen.zsh
  - echo "source ~/antigen.zsh; antigen bundle rylnd/shpec; antigen apply" > ~/.zshrc
  - echo "setopt sh_word_split" > ~/.zshenv
  - zsh ~/.zshrc
  - export SHELL=zsh

  - $HOME/.nvm/nvm.sh
  - nvm install 6 && nvm use 6
  - (cd test && npm install)

script:
  - zsh --version ; lynx --version
  - ./.travis-test.zsh

before_install:
  - sudo apt-get install zsh lynx
  - export SHELL=zsh

cache: apt

notifications:
  email: false
