# zsh shpec build draft
language: sh
env:
  matrix:
    - SHELL=bash
    - SHELL=zsh

install:
  # install antigen
  - curl -L git.io/antigen > ~/antigen.zsh
  - echo "source ~/antigen.zsh; antigen bundle rylnd/shpec; antigen apply" > ~/.zshrc
  - echo "setopt sh_word_split" > ~/.zshenv
  - zsh ~/.zshrc
  - sh -c "`curl -L https://raw.github.com/rylnd/shpec/master/install.sh`"

  - $HOME/.nvm/nvm.sh
  - nvm install 6 && nvm use 6
  - (cd test && npm install)

script:
  - lynx --version
  - |
        $SHELL --version
        if [ "$SHELL" = "zsh" ]; then
          ./.travis-test.zsh
        elif [ "$SHELL" = "bash"]]; then
          /usr/local/bin/shpec
        fi
before_install:
  - sudo apt-get install zsh lynx
  - export SHELL=zsh

cache: apt

notifications:
  email: false
