language: sh
env:
  - SHELL=zsh
install:
  - sh -c "`curl -L https://raw.github.com/rylnd/shpec/master/install.sh`"

  - $HOME/.nvm/nvm.sh
  - nvm install 6 && nvm use 6
  - (cd test && npm install)

script:
  - (cd test && node server.js)&
  - zsh --version
  - shpec

before_install:
  - sudo apt-get install zsh
  - export SHELL=zsh

notifications:
  email: false
